image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build-and-push:
  stage: build
  only:
    - main
    - merge_requests
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin
  script:
    - |
      DOCKER_IMAGE_NAME="$DOCKERHUB_USERNAME/anna"
      DOCKER_IMAGE_TAG="${CI_COMMIT_SHA:0:8}"
      
      docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
      docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:latest
      
      docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      docker push $DOCKER_IMAGE_NAME:latest
  after_script:
    - docker logout